### Get all services
GET http://localhost:3001/api/services HTTP/1.1

### Get all counters
GET http://localhost:3001/api/counters HTTP/1.1

### Get the next customer for the counter
GET http://localhost:3001/api/counters/1/next-customer HTTP/1.1