### Get all services
GET http://localhost:3001/api/services HTTP/1.1

### Get all counters
GET http://localhost:3001/api/counters HTTP/1.1

### counter is Occupied
PUT http://localhost:3001/api/counters/2/occupy HTTP/1.1

### disconnect Counter
PUT http://localhost:3001/api/counters/2/disconnect HTTP/1.1